# Local-only Terraform practice — no cloud account needed.
# Uses null_resource and local_file providers to simulate
# the same plan/apply/destroy workflow you would use with AWS.

# Simulates an "EC2 instance"
resource "null_resource" "app_server" {
  triggers = {
    instance_type = var.instance_type
    environment   = var.environment
    app_name      = var.app_name
  }

  provisioner "local-exec" {
    command = <<-CMD
      echo "======================================"
      echo " Provisioning app server"
      echo " Name:     ${var.app_name}-${var.environment}-server"
      echo " Type:     ${var.instance_type}"
      echo " Region:   ${var.aws_region}"
      echo "======================================"
    CMD
  }
}

# Simulates an "RDS database"
resource "null_resource" "database" {
  triggers = {
    db_name  = var.db_name
    db_user  = var.db_username
    env      = var.environment
  }

  provisioner "local-exec" {
    command = <<-CMD
      echo "======================================"
      echo " Provisioning database"
      echo " Name:     ${var.db_name}"
      echo " User:     ${var.db_username}"
      echo " Instance: ${var.db_instance_class}"
      echo "======================================"
    CMD
  }
}

# Simulates a "VPC"
resource "null_resource" "vpc" {
  triggers = {
    app  = var.app_name
    env  = var.environment
  }

  provisioner "local-exec" {
    command = "echo 'VPC created: ${var.app_name}-${var.environment}-vpc (10.0.0.0/16)'"
  }
}

# Creates a REAL local file — the .env for your app
# This is exactly what Terraform does in production (writes config files)
resource "local_file" "app_env" {
  filename        = "${path.module}/../.env.terraform"
  file_permission = "0600"

  content = <<-ENV
    # Generated by Terraform — do not edit manually
    # terraform apply regenerates this file

    APP_NAME=${var.app_name}
    ENVIRONMENT=${var.environment}
    NODE_ENV=${var.environment == "prod" ? "production" : "development"}

    DB_HOST=localhost
    DB_PORT=5432
    DB_NAME=${var.db_name}
    DB_USER=${var.db_username}
    DB_PASSWORD=${var.db_password}

    INSTANCE_TYPE=${var.instance_type}
    AWS_REGION=${var.aws_region}
  ENV
}

# Creates a REAL local inventory file for Ansible to read
resource "local_file" "ansible_inventory" {
  filename = "${path.module}/../ansible/inventory.ini"

  content = <<-INI
    # Generated by Terraform — do not edit manually
    # Run terraform apply to regenerate

    [app_servers]
    taskmanager-app ansible_host=localhost ansible_user=ec2-user

    [app_servers:vars]
    ansible_python_interpreter=/usr/bin/python3
    environment=${var.environment}
    app_name=${var.app_name}
  INI
}